'use client'

import Navbar from '@/components/Navbar'
import { useState, useEffect } from 'react'

interface Anniversary {
  id: number
  title: string
  date: string
  emoji: string
  isAutoGenerated: boolean
}

function getStartDate() {
  if (typeof window !== 'undefined') {
    return localStorage.getItem('coupleStartDate') || '2024-01-15'
  }
  return '2024-01-15'
}

function calcDaysBetween(from: string, to: string) {
  return Math.floor((new Date(to).getTime() - new Date(from).getTime()) / (1000 * 60 * 60 * 24))
}

function addDays(dateStr: string, days: number) {
  const d = new Date(dateStr)
  d.setDate(d.getDate() + days)
  return d.toISOString().split('T')[0]
}

function formatDate(dateStr: string) {
  const d = new Date(dateStr + 'T00:00:00')
  return `${d.getFullYear()}.${String(d.getMonth() + 1).padStart(2, '0')}.${String(d.getDate()).padStart(2, '0')}`
}

export default function AnniversaryPage() {
  const today = new Date().toISOString().split('T')[0]
  const [startDate, setStartDate] = useState('2024-01-15')
  const [showAdd, setShowAdd] = useState(false)
  const [newAnniv, setNewAnniv] = useState({ title: '', date: '', emoji: '💝' })
  const [customAnniversaries, setCustomAnniversaries] = useState<Anniversary[]>([])

  useEffect(() => {
    setStartDate(getStartDate())
    loadAnniversaries()
  }, [])

  const loadAnniversaries = () => {
    try {
      const saved = localStorage.getItem('customAnniversaries')
      if (saved) {
        setCustomAnniversaries(JSON.parse(saved))
      }
    } catch {
      // ignore
    }
  }

  // 자동 기념일
  const autoAnniversaries: Anniversary[] = [
    { id: -1, title: '100일', date: addDays(startDate, 100), emoji: '💯', isAutoGenerated: true },
    { id: -2, title: '200일', date: addDays(startDate, 200), emoji: '🎉', isAutoGenerated: true },
    { id: -3, title: '300일', date: addDays(startDate, 300), emoji: '✨', isAutoGenerated: true },
    { id: -4, title: '1주년', date: addDays(startDate, 365), emoji: '🎂', isAutoGenerated: true },
    { id: -5, title: '500일', date: addDays(startDate, 500), emoji: '🌟', isAutoGenerated: true },
    { id: -6, title: '2주년', date: addDays(startDate, 730), emoji: '💖', isAutoGenerated: true },
    { id: -7, title: '1000일', date: addDays(startDate, 1000), emoji: '👑', isAutoGenerated: true },
  ]

  const allAnniversaries = [...autoAnniversaries, ...customAnniversaries]
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())

  const upcoming = allAnniversaries.filter((a) => a.date >= today)
  const past = allAnniversaries.filter((a) => a.date < today).reverse()

  const getDDayText = (dateStr: string) => {
    const diff = calcDaysBetween(today, dateStr)
    if (diff === 0) return 'D-Day!'
    if (diff > 0) return `D-${diff}`
    return `D+${Math.abs(diff)}`
  }

  const handleAdd = (e: React.FormEvent) => {
    e.preventDefault()
    const newItem: Anniversary = {
      id: Date.now(),
      title: newAnniv.title,
      date: newAnniv.date,
      emoji: newAnniv.emoji,
      isAutoGenerated: false,
    }
    const updated = [...customAnniversaries, newItem]
    setCustomAnniversaries(updated)
    localStorage.setItem('customAnniversaries', JSON.stringify(updated))
    setShowAdd(false)
    setNewAnniv({ title: '', date: '', emoji: '💝' })
  }

  const emojis = ['💝', '💕', '🎂', '✈️', '🌸', '⭐', '🎁', '💍', '🏠', '🎵']

  return (
    <div className="min-h-screen bg-cream-50">
      <Navbar />

      <main className="max-w-2xl mx-auto px-4 py-8 pb-24 md:pb-8">
        <div className="flex items-center justify-between mb-6">
          <h1 className="font-handwriting text-3xl text-gray-600">기념일</h1>
          <button
            onClick={() => setShowAdd(true)}
            className="text-sm text-pink-400 hover:text-pink-500 px-3 py-1.5 border border-pink-200 rounded-full"
          >
            + 추가
          </button>
        </div>

        {/* 다가오는 기념일 */}
        <section className="mb-8">
          <h2 className="text-sm text-lavender-400 mb-3 ml-1">다가오는 기념일</h2>
          <div className="space-y-3">
            {upcoming.slice(0, 5).map((anniv) => (
              <div key={anniv.id} className="card-pastel p-4 flex items-center gap-4">
                <span className="text-3xl">{anniv.emoji}</span>
                <div className="flex-1">
                  <h3 className="text-sm font-bold text-gray-600">{anniv.title}</h3>
                  <p className="text-xs text-gray-400">{formatDate(anniv.date)}</p>
                </div>
                <span className="text-sm font-bold text-pink-400">{getDDayText(anniv.date)}</span>
              </div>
            ))}
          </div>
        </section>

        {/* 지난 기념일 */}
        <section>
          <h2 className="text-sm text-gray-400 mb-3 ml-1">지난 기념일</h2>
          <div className="space-y-2">
            {past.map((anniv) => (
              <div key={anniv.id} className="card-pastel p-3 flex items-center gap-4 opacity-70">
                <span className="text-2xl">{anniv.emoji}</span>
                <div className="flex-1">
                  <h3 className="text-sm text-gray-500">{anniv.title}</h3>
                  <p className="text-xs text-gray-400">{formatDate(anniv.date)}</p>
                </div>
                <span className="text-xs text-gray-400">{getDDayText(anniv.date)}</span>
              </div>
            ))}
          </div>
        </section>

        {/* 기념일 추가 모달 */}
        {showAdd && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 px-4">
            <div className="card-pastel p-6 w-full max-w-sm">
              <h3 className="font-handwriting text-xl text-gray-600 mb-4">기념일 추가</h3>
              <form onSubmit={handleAdd} className="space-y-4">
                <div>
                  <label className="block text-sm text-pink-400 mb-2 ml-1">이모지</label>
                  <div className="flex flex-wrap gap-2">
                    {emojis.map((emoji) => (
                      <button
                        key={emoji}
                        type="button"
                        onClick={() => setNewAnniv({ ...newAnniv, emoji })}
                        className={`text-2xl p-2 rounded-xl transition-all ${
                          newAnniv.emoji === emoji ? 'bg-pink-100 scale-110' : 'hover:bg-pink-50'
                        }`}
                      >
                        {emoji}
                      </button>
                    ))}
                  </div>
                </div>
                <div>
                  <label className="block text-sm text-pink-400 mb-1.5 ml-1">기념일 이름</label>
                  <input
                    type="text"
                    className="input-pastel"
                    placeholder="어떤 날이에요?"
                    value={newAnniv.title}
                    onChange={(e) => setNewAnniv({ ...newAnniv, title: e.target.value })}
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm text-pink-400 mb-1.5 ml-1">날짜</label>
                  <input
                    type="date"
                    className="input-pastel"
                    value={newAnniv.date}
                    onChange={(e) => setNewAnniv({ ...newAnniv, date: e.target.value })}
                    required
                  />
                </div>
                <div className="flex gap-3 pt-2">
                  <button type="button" onClick={() => setShowAdd(false)} className="btn-secondary">
                    취소
                  </button>
                  <button type="submit" className="btn-primary">
                    추가하기
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}
      </main>
    </div>
  )
}
